### ISSUE TITLE
datastorage read response hasError broken

### ISSUE THREAD

**Issue by mbretter** [wirecard/checkout-client-library#6]
datastorage read response hasError broken, const STATE_FAILURE has been redefined to 3 in WirecardCEE_QMore_DataStorage_Response_Read, while it is defined with a value of 1 in the abstract base class.

Therefore hasError() is not working as expected.

Solutuion redefine consts in WirecardCEE_QMore_DataStorage_Response_Read without redefining STATE_FAILURE

**Comment by jakubpolomsky** [comment]
Commit [96bb798](https://github.com/wirecard/checkout-client-library/commit/96bb798a3cfabe8d18dabdeedaa4738bb6809153) solves this issue.
